@startuml
skinparam activityFontSize 17
skinparam activityDiamondFontSize 17
skinparam activityArrowFontSize 17
scale 600 width
start
:Получение профиля температуры;
:Получение векторов величин Zh, Zdr, LDR, Kdr\n                 за один период накопления;
while (\nЦикл по каналам дальности\n) is (  Исполнение)

while (\nЦикл по классам гидрометеоров\n) is (  Исполнение)
split
   :Фазификация Zh;
   :Расчет решающих\n   правил для Zh и \n теку;
split again
   :Фазификация Zdr;
   :Расчет решающих\n   правил для Zdr;
split again
   :Фазификация LDR;
   :Расчет решающих\n   правил для LDR;
split again
   :Фазификация Kdp;
   :Расчет решающих\n   правил для Kdp;
end split

:Дефазификация и аккумуляция;

:Сравнение текущего максимального \n    значения аккумуляции с новым;

endwhile (Завершение   )

:Отброс классов с ошибочными измерениями;
:Выбор класса гидрометеора по максимуму значения аккумуляции;
:Расчет температуры на высоте радиолокационного\n             измерения по профилю температуры;


:Решение о наличии переохлажденной жидкости;

:Оценка опасности вероятного обледенения ВС;

endwhile (Завершение  )

:Сохранение результата в память ПК ;


stop
@enduml