@startuml
skinparam activityFontSize 17
skinparam activityDiamondFontSize 17
skinparam activityArrowFontSize 17
scale 600 width
start
:Получение векторов величин Zh, Zdr, LDR, Kdr\n                 за один период накопления;
while (\nЦикл по каналам дальности\n) is (  Исполнение)
:Выбор ориентации гидрометеора в пространстве;
:Выбор равнообъемного диаметра гидрометеора;
:Выбор отношения осей сфероида гидрометеора;
:Расчет Т-матрицы для выбранной
 формы и ориентации сфероида;

:Расчет комплексных амплитуд
прямого и обратного рассеяния;

:Накопление результата;


endwhile (Завершение   )
:Устреднение по ансамблю финального результата,
             расчет поляриметрических величин;
:Сохранение результата в память ПК ;


stop
@enduml