@startuml
skinparam activityFontSize 17
skinparam activityDiamondFontSize 17
skinparam activityArrowFontSize 17

'title Случай визуализации информации из ХД\n

|#FFFFFF|Пользователь(П)|
|#FFFFFF|Хранилище данных(ХД)|
|#FFFFFF|Графический\nинтерфейс(ГИ)|
|#FFFFFF|Ядро расчета(ЯР)|

|Пользователь(П)|
start
    :Запрос пользователя;
    |Графический\nинтерфейс(ГИ)|
    if (\n    Требуется ли\n  запросить новую\nинформацию из БД\n) then (Да)
        :Запрос извлечения\n  данных из базы;
        |Хранилище данных(ХД)|
        :Выдача данных из базы;
        |Графический\nинтерфейс(ГИ)|
    else (Нет)
    endif
    :Изменение ГИ;
    |Пользователь(П)|
    :Наблюдение результата;
stop
@enduml