@startuml
skinparam activityFontSize 17
skinparam activityDiamondFontSize 17
skinparam activityArrowFontSize 17
'title Случай изменения данных БД\n

|#FFFFFF|Ядро расчета(ЯР)|
|#FFFFFF|Пользователь(П)|
|#FFFFFF|Графический\nинтерфейс(ГИ)|
|#FFFFFF|Хранилище данных(ХД)|

|Пользователь(П)|
start
    :Запрос пользователя;
    |Графический\nинтерфейс(ГИ)|
    :Запрос извлечения\n  данных из базы;
    |Хранилище данных(ХД)|
    :Выдача данных\n      из базы;
    |Графический\nинтерфейс(ГИ)|
    :     Формирование\nграфической формы\n   редактирования\n   содержимого БД;
    |Пользователь(П)|
    if (\n Изменение\n требуется\n) then (Нет)
    stop
    else (Да)
    :Изменение информации\n   в графической форме ;
    |Графический\nинтерфейс(ГИ)|
    :Запрос на изменение\n        информации,\n  содержащейся в БД;
    |Хранилище данных(ХД)|
    if (\n      Требуется\nпредварительный\n          расчет\n) then (Да)
    |Ядро расчета(ЯР)|
    :Предварительный\n        расчет\n вспомогательной\n   информации;
    else (Нет)
    endif
    |Хранилище данных(ХД)|
    :Изменение информации,\n    содержащейся в БД;
stop
@enduml