@startuml
skinparam activityFontSize 17
skinparam activityDiamondFontSize 17
skinparam activityArrowFontSize 17
'title Случай добавления данных в БД\n

|#FFFFFF|Хранилище данных(ХД)|
|#FFFFFF|Ядро расчета(ЯР)|
|#FFFFFF|Пользователь(П)|
|#FFFFFF|Графический\nинтерфейс(ГИ)|

|Пользователь(П)|
start
    :Запрос пользователя;
    |Графический\nинтерфейс(ГИ)|
    if (\nТребуетсягенерация\n  новой информации\n) then (Да)
        :     Формирование\nграфической формы\nвыбора параметров\n  генерации данных;
        |Пользователь(П)|
        : Выбор формата и\nсценария генерации\nинформации для БД;
        |Ядро расчета(ЯР)|
        :     Формирование по\nполученному сценарию\n     двоичного файла,\n          содержащего\n    новую информацию ;
        : Сохранение\nполученного\n    файла в\n  память ПК;
    else (Нет)
    |Графический\nинтерфейс(ГИ)|
        :     Формирование\nграфическойформы\n        добавления\n   информации в БД\n;
    |Пользователь(П)|
    :   Выбор двоичного\nфайла, содержащего\n новую информацию\n      из памяти ПК;
    endif
    |Графический\nинтерфейс(ГИ)|
    :Запрос на изменение\n        информации,\n  содержащейся в БД;
    |Ядро расчета(ЯР)|
    :   Проверка полученных\nданных, предварительный\n расчет вспомогательной\n           информации;
    |Хранилище данных(ХД)|
    :   Изменение\n  информации,\nсодержащейся\n        в БД;
stop
@enduml