@startuml
scale 1200 width
skinparam activityFontSize 17
skinparam activityDiamondFontSize 17
skinparam activityArrowFontSize 17
'title Случай запуска и управления процедурой имитации\n
|#FFFFFF|Пользователь(П)|
|#FFFFFF|Графический\nинтерфейс(ГИ)|
|#FFFFFF|Ядро расчета(ЯР)|
|#FFFFFF|Хранилище данных(ХД)|

|Пользователь(П)|
start
    :Запрос пользователя;
    |Графический\nинтерфейс(ГИ)|
    :  Запрос извлечения\n      информации со\n          сценариями\nмоделирования из БД;
    |Хранилище данных(ХД)|
    :Выдача\nданных\nиз базы;
    |Графический\nинтерфейс(ГИ)|
    :Изменение ГИ;
    |Пользователь(П)|
    : Выбор сценария\nмоделирования и\n   запуск расчета;
    |Ядро расчета(ЯР)|
    fork
        repeat
        :  Timeout\n(Перерыв);
        :     Формирование\n       сообщения с\nсостоянием расчета;
        |Графический\nинтерфейс(ГИ)|
        :Изменение ГИ;
        |Пользователь(П)|
        :Визулизация\n процесса и\n управление\n  расчетом;
        |Ядро расчета(ЯР)|
        repeat while (\nПока пользователь\nне прервал расчет\n)
    fork again
        :      Запрос извлечения\nданных для выбранного\n         сценария из БД;
        |Хранилище данных(ХД)|
        :Выдача\nданных\nиз базы;
        |Ядро расчета(ЯР)|
        :  Выполнение процедуры\n         имитационного\n        моделирования\n сигнальной и помеховой\nобстановки в соответствии\n            со сценарием;
        :Конвертация результата\n     расчета в формат\n           МНРЛС-2015;
    end fork
            |Хранилище данных(ХД)|
        : Сохранение\nрезультата в\n память ПК и\n   создание\n записи в БД;
        |Ядро расчета(ЯР)|
    |Графический\nинтерфейс(ГИ)|
    :Изменение ГИ;
    |Пользователь(П)|
    :Визулизация\n результата\n    расчета;
stop
@enduml