@startuml
skinparam activityFontSize 17
skinparam activityDiamondFontSize 17
skinparam activityArrowFontSize 17
'title Случай отображения диагностической информации\n

|#FFFFFF|Пользователь(П)|
|#FFFFFF|Ядро расчета(ЯР)|
|#FFFFFF|Графический\nинтерфейс(ГИ)|
|#FFFFFF|Хранилище данных(ХД)|

|Графический\nинтерфейс(ГИ)|

repeat
fork
:  Формирование\n         запроса\nдиагности для ЯР;
|Ядро расчета(ЯР)|
: Сбор диагности\nи формирование\n        ответа;
|Графический\nинтерфейс(ГИ)|
:     Получение\nдиагности из ЯР;
fork again
:  Формирование\n         запроса\nдиагности для ХД;
|Хранилище данных(ХД)|
: Сбор диагности\nи формирование\n      ответа;
|Графический\nинтерфейс(ГИ)|
:     Получение\nдиагности из БД;
end merge
split
:Редактирование\nдиагностической\n      формы ГИ;
|Пользователь(П)|
:   Наблюдение\nдиагностической\n   информации;
|Графический\nинтерфейс(ГИ)|
detach
split again
:  Timeout\n(Перерыв);
end split
repeat while
@enduml