@startuml
skinparam activityFontSize 17
skinparam activityDiamondFontSize 17
skinparam activityArrowFontSize 17
start
:Извлечение файлов СИМ в память программы;

:Создание текстового файла имен I/O для ADWRS;
:Создание текстового файла ДН для ADWRS;
:Создание текстовых файлов МЯ для ADWRS;

while (\n    Пока расчет не завершен\nЦикл по периодам накопления\n)
:Создание текстового файла параметров;
:Создание текстового файла пути носителя;
:Создание текстового файла точечных дискретных излучателей;
:Расчет сигнала одного периода накопления в ADWRS;
:Чтение выходного бинарного файла ADWRS,\nконвертация в универсальный формат ИСПО;
:Сохранение проимитированного сигнала\n   за один период накопления в файл;
:                Переход на новый период накопления\n(положение носителя, направление луча сканирования);
endwhile

:Удаление созданных в ходе расчета текстовых файлов;

stop
@enduml