@startuml
skinparam activityFontSize 17
skinparam activityDiamondFontSize 17
skinparam activityArrowFontSize 17
start
:Извлечение файлов СИМ в память программы;

:Создание неизменных в процессе\nрасчета конфигурционных файлов;
:Создание текстовых файлов МЯ для ADWRS;

while (\n    Пока расчет не завершен\nЦикл по периодам накопления\n)
:Подготовка конфигурционных файлов ADWRS\n               для текущего такта расчета;
:Расчет сигнала одного периода накопления в ADWRS;
:Чтение выходного бинарного файла ADWRS,\nконвертация в универсальный формат ИСПО;
:Сохранение проимитированного сигнала\n   за один период накопления в файл;
:                Переход на новый период накопления\n(положение носителя, направление луча сканирования);
endwhile

:Удаление созданных в ходе расчета текстовых файлов;

stop
@enduml