@startuml
skinparam activityFontSize 17
skinparam activityDiamondFontSize 17
skinparam activityArrowFontSize 17
scale 1200 width
start
:Извлечение карты аэродрома в виде транспортных линий движения;
:    Получение конфигурации сеанса моделирования\n(информация о классах движущихся точечных целей);
:Нулевой такт - случайная расстановка движущихся\n         точечных целей по транспортным линиям;
while (\n   Пока расчет не завершен\nЦикл по периодам накопления\n) is (  Исполнение)
:    Создание контейнера для хранения моделирования\nодного такта положений движущихся точечных объектов;
while (\nПока не перебраны все движущиеся точечные объекты\n    Цикл по индексам движущихся точеных объектов\n) is (Исполнение)
:Расчет преращения положения объекта на транспортной линии при движении;
if (\nОбъект выходит за текущую транспортную линию?\n) then (  Да)
    if (\nСуществуют другие траспортные линии,\n      начинающиеся из конца текущей\n) then (Да   )
        :        Случайный выбор новой\nтранспортной линии, начинающейся\nиз конца текущей траспортной линии;
    else (  Нет)
        :        Случайный выбор новой\nтранспортной линии, начинающейся\n     на границе района интереса;
    endif
    :          Новая траспортная линия становится текущей,\nпредыдущим положением объекта считается начало линии;
else ( Нет)
endif
:Расчет нового положения объекта на траспортной линии;
:Расчет компонент вектора скорости объекта для нового положения;
:Сохранение объекта в контейнер объектов текущего такта;
endwhile (Заверщение   )
:Сохранение результата (контейнера объектов за один такт) в память ПК ;
endwhile (Завершение   )
:Заполнение заголовка со служебной информацией в финальном файле;
stop
@enduml