@startuml
skinparam activityFontSize 17
skinparam activityDiamondFontSize 17
skinparam activityArrowFontSize 17
scale 1200 width
start
:Извлечение файла сигнала в универсальном формате в память;
:Извлечение файла пути носителя для соотвествующего СИМ в память;
:Выбор множителя для конвертации в аппаратные единицы АФАР МН РЛС2015;
while (\n   Пока расчет не завершен.\nЦикл по периодам накопления\n) is (  Исполнение)
    : Извлечение пакета сигнала в универсальном\nформате для текущего такта из файла сигнала;
    :Извлечение из файла пути информации о текущем такте;

    while (\nПока пакет сигнала в универсальном формате не\n    обработан. Цикл по номеру импульса в пачке\n) is (   Исполнение)
        :Создание пустого пакета в формате МН РЛС2015 для наполнения;
        : Заполнение заголовка пакета в формате МН РЛС2015\nпо данным для текущего такта из файла пути носителя;
        :Заполнение информационной части пакета (отчеты амплитуд\nпо каналам дальности) - одна квадратура сигнала из пакета в\n      универстальном формате, умноженная на множитель\n               конвертации и переведеная формат short;
        :Сохранение результата (сковертированный\nпакет в формате МН РЛС2015) в память ПК ;
    endwhile (Завершение  )
endwhile (Завершение   )

stop
@enduml