@startuml
skinparam activityFontSize 17
skinparam activityDiamondFontSize 17
skinparam activityArrowFontSize 17
scale 1200 width
start
:Извлечение карты аэродрома в виде полигонов объектов в память программы ;
:Предварительный расчет координат границ для зон аппроксимации ;
:Создание контейнера для записи выходной структуры точечных файлов - A  ;


while (\nПока не перебраны все контура-элементы\nЦикл по индексам контуров поверхностей \n) is (  Исполнение)
:Выбор контура поверхности определенного типа по индексу ;
:Выбор УЭПР для данного контура по типу поверхности - σ;
while (\nПока не перебраны все зоны аппроксимации\n      Цикл по номерам зон аппроксимации\n) is (Исполнение)
:Выбор зоны аппроксимации по номеру зоны аппроксимации ;
:Расчет площади фигуры, образованной пересечением текущей \n     зоны аппроксимации и текущего контура поверхности - S ;
:Прибавление для элемента контейнера А под индексом номера \n    зоны аппроксимации величины дополнительного ЭПР = S ∙ σ ;
endwhile (Заверщение   )
endwhile (Завершение   )
:Сохранение результата в память ПК ;
:Удаление созданных в ходе расчета текстовых вспомогательных файлов ;

stop
@enduml