@startuml
box Ядро расчета #lightblue
participant Управление
participant Метео
participant Воздух
participant Земля
participant Помехи
participant Конвертация
end box
Database     ХД #lightgreen

[-> Управление: Запуск расчета по\nконкретному сценарию
activate Управление
Управление -> ХД: Запрос файлов СИМ
activate ХД
ХД -> ХД: Извлечение СИМ
Управление <- ХД: Набор файлов для конкретного СИМ
deactivate ХД
Управление --> Метео: Файлы СИМ
activate Метео
Управление --> Воздух: Файлы СИМ
activate Воздух

Управление --> Земля: Файлы СИМ
activate Земля

Управление --> Помехи: Файлы СИМ
activate Помехи

Метео -> Метео: Расчет\nсигнала\nот МЯ
Воздух -> Воздух: Расчет\nсигнала\nот ВО
Земля -> Земля: Расчет\nсигнала\nот Земли
Помехи -> Помехи: Расчет\nсигнала\nот Помех

... Ожидание ответа от всех расчетных блоков ...
Управление <-- Метео: Сигнал от МЯ
deactivate Метео
Управление <-- Воздух: Сигнал от ВО
deactivate Воздух
Управление <-- Земля: Сигнал от Земли
deactivate Земля
Управление <-- Помехи: Сигнал от Помех
deactivate Помехи
Управление -> Управление: Объединение\nполученных\nсигналов
Управление -> Конвертация: Суммарный сигнал в универсальном формате
activate Конвертация
Конвертация -> Конвертация: Конвертация\nсигнала в формат\nМН РЛС-2015
Управление <- Конвертация: Суммарный сигнал в формате МН РЛС-2015
deactivate Конвертация
Управление --> ХД: Результат моделирования
activate ХД
ХД -> ХД: Сохранение\nрезультата\nмоделирования

[<- Управление: Информация об\nуспешности расчета
deactivate Управление
deactivate ХД
@enduml