@startuml
scale 600 width
[*] -right-> Отображение_СИМ : [Начало]

Отображение_СИМ --> Отображение_СИМ : другой продукт
Отображение_СИМ --> Изменение_СИМ
Отображение_СИМ --> Управление_расчетом
Изменение_СИМ --> Отображение_СИМ
Управление_расчетом --> Отображение_СИМ

Управление_расчетом -->[*]
Изменение_СИМ -->[*]
Отображение_СИМ -->[*]

@enduml