@startuml
scale 600 width
[*] -right-> Бездействие : [Начало]

Бездействие --> Обработка_команд
Обработка_команд -up-> Бездействие

state Обработка_команд {

  Выбор_операции --> Расчет
  Выбор_операции --> Подготовка
  Выбор_операции --> Диагностика
  Выбор_операции -right-> [*] : Завершение
}

@enduml