@startuml
scale 600 width
[*] -right-> Бездействие : [Начало]

Бездействие --> Обработка_команд
Обработка_команд --> Бездействие


state Обработка_команд {

  Выбор_операции --> Извлечение
  Выбор_операции --> Добавление
  Выбор_операции --> Изменение
  Выбор_операции --> Удаление
  Выбор_операции --> Диагностика
  Выбор_операции -right-> [*] : Завершение

}

@enduml